FROM golang:1.21 AS builder              
WORKDIR /app
COPY go.mod go.sum ./

RUN go mod download 
COPY . .
RUN CGO_ENABLED=0 go build -o /app/main


FROM gcr.io/distroless/static-debian12:latest-amd64   
WORKDIR /app                   
COPY --from=builder /app/main /app/main            
EXPOSE 8080 9090
CMD ["/app/main"]